//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineRepair.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MachineRepair.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger.
        /// </summary>
        internal static string Program_Main_Danger {
            get {
                return ResourceManager.GetString("Program_Main_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Program_Main_Status {
            get {
                return ResourceManager.GetString("Program_Main_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Size.
        /// </summary>
        internal static string String_CalculateSize {
            get {
                return ResourceManager.GetString("String_CalculateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Temps.
        /// </summary>
        internal static string String_CleanTemps {
            get {
                return ResourceManager.GetString("String_CleanTemps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger.
        /// </summary>
        internal static string String_Danger {
            get {
                return ResourceManager.GetString("String_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to docAlpha Station Error..
        /// </summary>
        internal static string String_DocalphaStationError {
            get {
                return ResourceManager.GetString("String_DocalphaStationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (does not exists).
        /// </summary>
        internal static string String_DoesNotExists {
            get {
                return ResourceManager.GetString("String_DoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you REALLY like to uninstall the {0}?.
        /// </summary>
        internal static string String_DoYouReallyLikeToUninstall {
            get {
                return ResourceManager.GetString("String_DoYouReallyLikeToUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string String_Error {
            get {
                return ResourceManager.GetString("String_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening the host.
        /// </summary>
        internal static string String_ErrorWhileOpeningHost {
            get {
                return ResourceManager.GetString("String_ErrorWhileOpeningHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to disconnect from the server.
        /// </summary>
        internal static string String_ErrorWhileTryingToDisconnectFromServer {
            get {
                return ResourceManager.GetString("String_ErrorWhileTryingToDisconnectFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to initialize server log: .
        /// </summary>
        internal static string String_ErrorWhileTryingToInitializeServerLog {
            get {
                return ResourceManager.GetString("String_ErrorWhileTryingToInitializeServerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to retrieve the service information. Probably service is not installed.
        /// </summary>
        internal static string String_ErrorWhileTryingToRetrieveServiceInfo {
            get {
                return ResourceManager.GetString("String_ErrorWhileTryingToRetrieveServiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to stop the host listener.
        /// </summary>
        internal static string String_ErrorWhileTryingToStopHostListener {
            get {
                return ResourceManager.GetString("String_ErrorWhileTryingToStopHostListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to stop the Recognition.
        /// </summary>
        internal static string String_ErrorWhileTryingToStopRecognition {
            get {
                return ResourceManager.GetString("String_ErrorWhileTryingToStopRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented.
        /// </summary>
        internal static string String_NotImplemented {
            get {
                return ResourceManager.GetString("String_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Calculation.
        /// </summary>
        internal static string String_PauseCalculation {
            get {
                return ResourceManager.GetString("String_PauseCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Cleaning.
        /// </summary>
        internal static string String_PauseCleaning {
            get {
                return ResourceManager.GetString("String_PauseCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        internal static string String_PleaseWait {
            get {
                return ResourceManager.GetString("String_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason: .
        /// </summary>
        internal static string String_Reason {
            get {
                return ResourceManager.GetString("String_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition Service Stopped.
        /// </summary>
        internal static string String_RecognitionServiceStopped {
            get {
                return ResourceManager.GetString("String_RecognitionServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition station configuration program.
        /// </summary>
        internal static string String_RecognitionStationConfigurationProgram {
            get {
                return ResourceManager.GetString("String_RecognitionStationConfigurationProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition station configuration program: Unhadled exception.
        /// </summary>
        internal static string String_RecognitionStationConfigurationProgramUn {
            get {
                return ResourceManager.GetString("String_RecognitionStationConfigurationProgramUn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Size Calculation.
        /// </summary>
        internal static string String_ResumeSizeCalculation {
            get {
                return ResourceManager.GetString("String_ResumeSizeCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Temps Cleaning.
        /// </summary>
        internal static string String_ResumeTempsCleaning {
            get {
                return ResourceManager.GetString("String_ResumeTempsCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See logs in folder:.
        /// </summary>
        internal static string String_SeeLogsInFolder {
            get {
                return ResourceManager.GetString("String_SeeLogsInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is already installed. Press OK..
        /// </summary>
        internal static string String_ServiceAlreadyInstalledPressOk {
            get {
                return ResourceManager.GetString("String_ServiceAlreadyInstalledPressOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service failed to start. Reason: .
        /// </summary>
        internal static string String_ServiceFailedToStartReason {
            get {
                return ResourceManager.GetString("String_ServiceFailedToStartReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not installed.
        /// </summary>
        internal static string String_ServiceNotInstalled {
            get {
                return ResourceManager.GetString("String_ServiceNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is Started.
        /// </summary>
        internal static string String_ServiceStarted {
            get {
                return ResourceManager.GetString("String_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Status: .
        /// </summary>
        internal static string String_ServiceStatus {
            get {
                return ResourceManager.GetString("String_ServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is Stopped.
        /// </summary>
        internal static string String_ServiceStopped {
            get {
                return ResourceManager.GetString("String_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Service.
        /// </summary>
        internal static string String_StartService {
            get {
                return ResourceManager.GetString("String_StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string String_Status {
            get {
                return ResourceManager.GetString("String_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Service.
        /// </summary>
        internal static string String_StopService {
            get {
                return ResourceManager.GetString("String_StopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed the {0}.
        /// </summary>
        internal static string String_SuccessfullyInstalled {
            get {
                return ResourceManager.GetString("String_SuccessfullyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully uninstalled the {0}.
        /// </summary>
        internal static string String_SuccessfullyUninstalled {
            get {
                return ResourceManager.GetString("String_SuccessfullyUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps Cleaned: {0} Mb.
        /// </summary>
        internal static string String_TempsCleanedMb {
            get {
                return ResourceManager.GetString("String_TempsCleanedMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps Cleaned: {0} Mb (unfinished).
        /// </summary>
        internal static string String_TempsCleanedMbUnfinished {
            get {
                return ResourceManager.GetString("String_TempsCleanedMbUnfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps Size: {0} Mb.
        /// </summary>
        internal static string String_TempsSizeMb {
            get {
                return ResourceManager.GetString("String_TempsSizeMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps Size: {0} Mb (unfinished).
        /// </summary>
        internal static string String_TempsSizeMbUnfinished {
            get {
                return ResourceManager.GetString("String_TempsSizeMbUnfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to start service... .
        /// </summary>
        internal static string String_TryingToStartService {
            get {
                return ResourceManager.GetString("String_TryingToStartService", resourceCulture);
            }
        }
    }
}
